//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nutritionApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class comida
    {
        public int idComida { get; set; }
        public int idPlan { get; set; }
        public string tiempoComida { get; set; }
        public int idReceta { get; set; }
    
        public virtual planNutricional planNutricional { get; set; }
        public virtual receta receta { get; set; }
    }
}
