//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nutritionApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingrediente
    {
        public ingrediente()
        {
            this.ingrediente_receta = new HashSet<ingrediente_receta>();
            this.usuarios = new HashSet<usuario>();
        }
    
        public int idIngrediente { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<ingrediente_receta> ingrediente_receta { get; set; }
        public virtual ICollection<usuario> usuarios { get; set; }
    }
}
