//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nutritionApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingrediente_receta
    {
        public int idReceta { get; set; }
        public int idIngrediente { get; set; }
        public float cantidad { get; set; }
        public string medida { get; set; }
        public string observaciones { get; set; }
    
        public virtual ingrediente ingrediente { get; set; }
        public virtual receta receta { get; set; }
    }
}
