//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nutritionApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class planNutricional
    {
        public planNutricional()
        {
            this.comidas = new HashSet<comida>();
        }
    
        public int idPlan { get; set; }
        public int idUsuario { get; set; }
        public System.DateTime fecha { get; set; }
        public string carbos { get; set; }
        public string proteinas { get; set; }
        public string grasas { get; set; }
        public string azucares { get; set; }
        public int cantComidas { get; set; }
        public Nullable<int> calorias { get; set; }
    
        public virtual ICollection<comida> comidas { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
