//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nutritionApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.imcs = new HashSet<imc>();
            this.medicions = new HashSet<medicion>();
            this.planNutricionals = new HashSet<planNutricional>();
            this.ingredientes = new HashSet<ingrediente>();
        }
    
        public int idUsuario { get; set; }
        public byte[] foto { get; set; }
        public string cedula { get; set; }
        public string genero { get; set; }
        public System.DateTime fechaNac { get; set; }
        public string nombre { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public string direccion { get; set; }
        public string telefono1 { get; set; }
        public byte estatura { get; set; }
        public float peso { get; set; }
        public string proposito { get; set; }
        public string correo { get; set; }
        public string usuario1 { get; set; }
        public string contrasena { get; set; }
        public string tipoUsuario { get; set; }
    
        public virtual ICollection<imc> imcs { get; set; }
        public virtual ICollection<medicion> medicions { get; set; }
        public virtual ICollection<planNutricional> planNutricionals { get; set; }
        public virtual ICollection<ingrediente> ingredientes { get; set; }
    }
}
